language: shell

os:
  - linux
  - osx
  - windows
install:
  - python setup.py install
script:
  - python setup.py test
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd docs && make clean && make html && cd ..; fi
after_success:
  - codecov
notifications:
  email: false
