language: shell

os:
  - linux
  - osx
  - windows
install:
  - pip install networkx
  - pip install tqdm
  - pip install python-louvain
  - pip install pandas
  - pip install numpy
  - pip install six
  - python setup.py install
script:
  - python setup.py test
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd docs && make clean && make html && cd ..; fi
after_success:
  - codecov
notifications:
  email: false
